apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  AZP_TOKEN: 'YOUR PAT TOKEN'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: '<THE URL FROM YOUR PUBLISHED IMAGE OM CR>'
        env:
          - name: AZP_URL
            value: "https://<YOUR ORGANIZATION NAME FROM DEVOPS>.visualstudio.com"
          - name: AZP_POOL
            value: "<NAME OF YOUR AGENT POOL>"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock